import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "antd/dist/reset.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { AntdThemeProvider } from "../components/Themes/AntdThemeProvider";
import { ThemeProvider } from "Nova/Provider/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "StudyWork",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-slate-900`}
      >
        <ThemeProvider>             {/* ← Bọc từ đây */}
          <AntdThemeProvider>
            <AntdRegistry>
              {children}
            </AntdRegistry>
          </AntdThemeProvider>
        </ThemeProvider> 
      </body>
    </html>
  );
}
